import assert from "node:assert/strict";
import type { AddressInfo, Server } from "node:net";
import { after, before, test } from "node:test";
import { PatientStoryStatus, UserRole } from "@prisma/client";
import dotenv from "dotenv";

dotenv.config({ override: true });
process.env.NODE_ENV = "test";
process.env.DATABASE_URL ??= "postgresql://USERNAME:PASSWORD@localhost:5432/DATABASE_NAME?schema=public";
process.env.JWT_ACCESS_SECRET ??= "integration-test-access-secret";
process.env.JWT_REFRESH_SECRET ??= "integration-test-refresh-secret";
process.env.JWT_ACCESS_EXPIRES_IN ??= "15m";
process.env.JWT_REFRESH_EXPIRES_IN ??= "7d";

let server: Server; let baseUrl: string; let patientId: string; let otherPatientId: string; let adminId: string; let doctorId: string;
const storyIds: string[] = []; const testKey = `phase1_15-${Date.now()}`;

before(async () => {
  const { default: app } = await import("../src/app"); const { prisma } = await import("../src/database/prisma");
  const users = await Promise.all([createUser(prisma, "patient", UserRole.PATIENT), createUser(prisma, "other", UserRole.PATIENT), createUser(prisma, "admin", UserRole.OPS_ADMIN), createUser(prisma, "doctor", UserRole.DOCTOR)]);
  [patientId, otherPatientId, adminId, doctorId] = users.map((user) => user.id);
  server = await new Promise<Server>((resolve, reject) => { const listener = app.listen(0, "127.0.0.1", () => resolve(listener)); listener.once("error", reject); });
  const address = server.address(); assert.ok(address && typeof address !== "string"); const { address: host, port } = address as AddressInfo; baseUrl = `http://${host}:${port}`;
});

after(async () => { const { prisma } = await import("../src/database/prisma"); await prisma.patientStory.deleteMany({ where: { id: { in: storyIds } } }); await prisma.user.deleteMany({ where: { id: { in: [patientId, otherPatientId, adminId, doctorId] } } }); const { resetPrivateStorageProvider } = await import("../src/storage/private-storage"); resetPrivateStorageProvider(); await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); });

test("published stories are visible, unpublished stories are hidden, and pagination works", async () => { const published = await createStory({ displayName: "Demo published", consentGiven: true, status: PatientStoryStatus.APPROVED, isPublished: true }); const draft = await createStory({ displayName: "Demo draft", consentGiven: false, status: PatientStoryStatus.DRAFT, isPublished: false }); const list = await request("GET", "/api/v1/stories?page=1&pageSize=1", await tokenFor(patientId)); const detail = await request("GET", `/api/v1/stories/${published.id}`, await tokenFor(patientId)); const hidden = await request("GET", `/api/v1/stories/${draft.id}`, await tokenFor(patientId)); assert.equal(list.body.data.pagination.total, 1); assert.equal(list.body.data.items[0].storyId, published.id); assert.equal(detail.status, 200); assert.equal(detail.body.data.storyId, published.id); assert.equal(detail.body.data.consentGiven, undefined); assert.equal(hidden.status, 404); });

test("admin can list, create, edit, and review stories", async () => { const list = await request("GET", "/api/v1/admin/stories", await tokenFor(adminId, UserRole.OPS_ADMIN)); const created = await request("POST", "/api/v1/admin/stories", await tokenFor(adminId, UserRole.OPS_ADMIN), { displayName: "Admin demo story", story: "Fictional story content.", consentGiven: true, consentTextVersion: "v1" }); const storyId = created.body.data.storyId as string; storyIds.push(storyId); const edited = await request("PATCH", `/api/v1/admin/stories/${storyId}`, await tokenFor(adminId, UserRole.OPS_ADMIN), { displayName: "Edited demo story" }); const underReview = await request("PATCH", `/api/v1/admin/stories/${storyId}/status`, await tokenFor(adminId, UserRole.OPS_ADMIN), { status: "UNDER_REVIEW" }); const approved = await request("PATCH", `/api/v1/admin/stories/${storyId}/status`, await tokenFor(adminId, UserRole.OPS_ADMIN), { status: "APPROVED" }); const adminDetail = await request("GET", `/api/v1/admin/stories/${storyId}`, await tokenFor(adminId, UserRole.OPS_ADMIN)); assert.equal(list.status, 200); assert.equal(created.body.data.createdBy.userId, adminId); assert.equal(edited.body.data.displayName, "Edited demo story"); assert.equal(underReview.body.data.status, "UNDER_REVIEW"); assert.equal(approved.body.data.status, "APPROVED"); assert.equal(adminDetail.body.data.consentGiven, true); assert.equal(adminDetail.body.data.updatedBy.userId, adminId); });

test("consent is required for publication and invalid transitions are rejected", async () => { const story = await createStory({ displayName: "No consent", consentGiven: false, status: PatientStoryStatus.APPROVED, isPublished: false }); const publish = await request("PATCH", `/api/v1/admin/stories/${story.id}/publish`, await tokenFor(adminId, UserRole.OPS_ADMIN), { isPublished: true }); const transition = await request("PATCH", `/api/v1/admin/stories/${story.id}/status`, await tokenFor(adminId, UserRole.OPS_ADMIN), { status: "APPROVED" }); assert.equal(publish.status, 409); assert.equal(publish.body.error.code, "STORY_PUBLICATION_REQUIRES_APPROVAL"); assert.equal(transition.status, 409); assert.equal(transition.body.error.code, "PATIENT_STORY_STATUS_CONFLICT"); });

test("approved consented story can publish and unpublish", async () => { const story = await createStory({ displayName: "Consent story", consentGiven: true, status: PatientStoryStatus.DRAFT, isPublished: false }); await request("PATCH", `/api/v1/admin/stories/${story.id}/status`, await tokenFor(adminId, UserRole.OPS_ADMIN), { status: "UNDER_REVIEW" }); await request("PATCH", `/api/v1/admin/stories/${story.id}/status`, await tokenFor(adminId, UserRole.OPS_ADMIN), { status: "APPROVED" }); const published = await request("PATCH", `/api/v1/admin/stories/${story.id}/publish`, await tokenFor(adminId, UserRole.OPS_ADMIN), { isPublished: true }); const visible = await request("GET", `/api/v1/stories/${story.id}`, await tokenFor(patientId)); const unpublished = await request("PATCH", `/api/v1/admin/stories/${story.id}/publish`, await tokenFor(adminId, UserRole.OPS_ADMIN), { isPublished: false }); const hidden = await request("GET", `/api/v1/stories/${story.id}`, await tokenFor(patientId)); assert.equal(published.body.data.isPublished, true); assert.equal(visible.status, 200); assert.equal(unpublished.body.data.isPublished, false); assert.equal(hidden.status, 404); });

test("admin photo upload uses private storage and public response exposes temporary access only", async () => { const story = await createStory({ displayName: "Photo story", consentGiven: true, status: PatientStoryStatus.APPROVED, isPublished: true }); const form = new FormData(); form.append("file", new Blob([Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])], { type: "image/png" }), "story.png"); const response = await requestForm("POST", `/api/v1/admin/stories/${story.id}/photo`, await tokenFor(adminId, UserRole.OPS_ADMIN), form); const visible = await request("GET", `/api/v1/stories/${story.id}`, await tokenFor(patientId)); const { prisma } = await import("../src/database/prisma"); const record = await prisma.patientStory.findUnique({ where: { id: story.id } }); assert.equal(response.status, 201); assert.ok(record?.photoStorageKey?.startsWith("patient-stories/")); assert.equal(visible.body.data.photo.access.reference.startsWith("private://"), true); assert.equal("photoStorageKey" in visible.body.data, false); });

test("roles and invalid payloads are rejected", async () => { const unauthenticated = await request("GET", "/api/v1/stories"); const patientAdmin = await request("GET", "/api/v1/admin/stories", await tokenFor(patientId)); const doctor = await request("GET", "/api/v1/stories", await tokenFor(doctorId, UserRole.DOCTOR)); const invalid = await request("POST", "/api/v1/admin/stories", await tokenFor(adminId, UserRole.OPS_ADMIN), { displayName: "", story: "" }); assert.equal(unauthenticated.status, 401); assert.equal(patientAdmin.status, 403); assert.equal(doctor.status, 403); assert.equal(invalid.status, 400); assert.equal(invalid.body.error.code, "VALIDATION_ERROR"); });

async function createStory(input: { displayName: string; consentGiven: boolean; status: PatientStoryStatus; isPublished: boolean }) { const { prisma } = await import("../src/database/prisma"); const story = await prisma.patientStory.create({ data: { displayName: input.displayName, story: "Fictional demo story content.", consentGiven: input.consentGiven, consentTextVersion: input.consentGiven ? "test-v1" : null, status: input.status, isPublished: input.isPublished, publishedAt: input.isPublished ? new Date() : null, createdById: adminId, updatedById: adminId } }); storyIds.push(story.id); return story; }
async function createUser(prisma: typeof import("../src/database/prisma").prisma, name: string, role: UserRole) { return prisma.user.create({ data: { fullName: `${testKey} ${name}`, email: `${testKey}-${name}@example.com`, phone: `+1555${String(Math.floor(Math.random() * 10_000_000)).padStart(7, "0")}`, role, isVerified: true } }); }
async function tokenFor(userId: string, role = UserRole.PATIENT) { const { generateAccessToken } = await import("../src/services/jwt"); return generateAccessToken({ userId, role }); }
async function request(method: string, path: string, token?: string, body?: Record<string, unknown>) { const response = await fetch(`${baseUrl}${path}`, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: response.status, body: await response.json() as Record<string, any> }; }
async function requestForm(method: string, path: string, token: string, body: FormData) { const response = await fetch(`${baseUrl}${path}`, { method, headers: { Authorization: `Bearer ${token}` }, body }); return { status: response.status, body: await response.json() as Record<string, any> }; }
