import assert from "node:assert/strict";
import type { AddressInfo, Server } from "node:net";
import { after, before, test } from "node:test";
import { ClinicalTrialSource, ClinicalTrialStatus, TrialInterestStatus, UserRole } from "@prisma/client";
import dotenv from "dotenv";

dotenv.config({ override: true });
process.env.NODE_ENV = "test";
process.env.DATABASE_URL ??= "postgresql://USERNAME:PASSWORD@localhost:5432/DATABASE_NAME?schema=public";
process.env.JWT_ACCESS_SECRET ??= "integration-test-access-secret";
process.env.JWT_REFRESH_SECRET ??= "integration-test-refresh-secret";
process.env.JWT_ACCESS_EXPIRES_IN ??= "15m";
process.env.JWT_REFRESH_EXPIRES_IN ??= "7d";

let server: Server; let baseUrl: string; let patientId: string; let otherPatientId: string; let adminId: string; let doctorId: string;
const trialIds: string[] = []; const interestIds: string[] = []; const testKey = `phase1_14-${Date.now()}`;

before(async () => {
  const { default: app } = await import("../src/app"); const { prisma } = await import("../src/database/prisma");
  const users = await Promise.all([createUser(prisma, "patient", UserRole.PATIENT), createUser(prisma, "other", UserRole.PATIENT), createUser(prisma, "admin", UserRole.OPS_ADMIN), createUser(prisma, "doctor", UserRole.DOCTOR)]);
  [patientId, otherPatientId, adminId, doctorId] = users.map((user) => user.id);
  server = await new Promise<Server>((resolve, reject) => { const listener = app.listen(0, "127.0.0.1", () => resolve(listener)); listener.once("error", reject); });
  const address = server.address(); assert.ok(address && typeof address !== "string"); const { address: host, port } = address as AddressInfo; baseUrl = `http://${host}:${port}`;
});

after(async () => { const { prisma } = await import("../src/database/prisma"); await prisma.trialInterest.deleteMany({ where: { id: { in: interestIds } } }); await prisma.clinicalTrial.deleteMany({ where: { id: { in: trialIds } } }); await prisma.user.deleteMany({ where: { id: { in: [patientId, otherPatientId, adminId, doctorId] } } }); await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); });

test("patient can list, filter, search, paginate, and retrieve published trials", async () => {
  const published = await createTrial({ title: "Demo supportive care trial", sourceTrialId: "demo-1", isPublished: true, status: ClinicalTrialStatus.RECRUITING }); await createTrial({ title: "Demo planning trial", sourceTrialId: "demo-2", isPublished: true, status: ClinicalTrialStatus.COMPLETED }); await createTrial({ title: "Draft trial", sourceTrialId: "draft-1", isPublished: false });
  const list = await request("GET", "/api/v1/trials?page=1&pageSize=1", await tokenFor(patientId)); const search = await request("GET", "/api/v1/trials?search=supportive", await tokenFor(patientId)); const status = await request("GET", "/api/v1/trials?status=RECRUITING", await tokenFor(patientId)); const detail = await request("GET", `/api/v1/trials/${published.id}`, await tokenFor(patientId));
  assert.equal(list.body.data.pagination.total, 2); assert.equal(list.body.data.items.length, 1); assert.equal(search.body.data.items[0].trialId, published.id); assert.equal(status.body.data.items[0].trialId, published.id); assert.equal(detail.status, 200); assert.equal(detail.body.data.trialId, published.id);
});

test("patient cannot view unpublished trials", async () => { const draft = await createTrial({ title: "Hidden demo trial", sourceTrialId: "hidden-1", isPublished: false }); const list = await request("GET", "/api/v1/trials", await tokenFor(patientId)); const detail = await request("GET", `/api/v1/trials/${draft.id}`, await tokenFor(patientId)); assert.equal(list.body.data.items.some((item: { trialId: string }) => item.trialId === draft.id), false); assert.equal(detail.status, 404); });

test("patient can submit and list only their own interest, with duplicate protection", async () => { const trial = await createTrial({ title: "Interest demo trial", sourceTrialId: "interest-1", isPublished: true }); const created = await request("POST", `/api/v1/trials/${trial.id}/interest`, await tokenFor(patientId), { notes: "Please contact me" }); interestIds.push(created.body.data.interestId); const duplicate = await request("POST", `/api/v1/trials/${trial.id}/interest`, await tokenFor(patientId), {}); const own = await request("GET", "/api/v1/trials/interests", await tokenFor(patientId)); const other = await request("GET", "/api/v1/trials/interests", await tokenFor(otherPatientId)); assert.equal(created.status, 201); assert.equal(created.body.data.status, "SUBMITTED"); assert.equal(duplicate.status, 409); assert.equal(duplicate.body.error.code, "TRIAL_INTEREST_EXISTS"); assert.equal(own.body.data.length, 1); assert.equal(other.body.data.length, 0); });

test("admin can create, edit, publish, and list trials", async () => { const created = await request("POST", "/api/v1/admin/trials", await tokenFor(adminId, UserRole.OPS_ADMIN), trialInput({ sourceTrialId: "admin-1" })); const trialId = created.body.data.trialId as string; trialIds.push(trialId); const adminList = await request("GET", "/api/v1/admin/trials?isPublished=false", await tokenFor(adminId, UserRole.OPS_ADMIN)); const edited = await request("PATCH", `/api/v1/admin/trials/${trialId}`, await tokenFor(adminId, UserRole.OPS_ADMIN), { title: "Edited demo trial" }); const published = await request("PATCH", `/api/v1/admin/trials/${trialId}/publish`, await tokenFor(adminId, UserRole.OPS_ADMIN), { isPublished: true }); const patient = await request("GET", `/api/v1/trials/${trialId}`, await tokenFor(patientId)); const { prisma } = await import("../src/database/prisma"); const record = await prisma.clinicalTrial.findUnique({ where: { id: trialId } }); assert.equal(created.status, 201); assert.equal(created.body.data.createdBy.userId, adminId); assert.equal(adminList.body.data.items.some((item: { trialId: string }) => item.trialId === trialId), true); assert.equal(edited.body.data.title, "Edited demo trial"); assert.equal(edited.body.data.updatedBy.userId, adminId); assert.equal(published.body.data.isPublished, true); assert.equal(patient.status, 200); assert.equal(record?.createdById, adminId); assert.equal(record?.updatedById, adminId); });

test("duplicate source identity and invalid payloads are rejected", async () => { const first = await request("POST", "/api/v1/admin/trials", await tokenFor(adminId, UserRole.OPS_ADMIN), trialInput({ sourceTrialId: "duplicate-source" })); trialIds.push(first.body.data.trialId); const duplicate = await request("POST", "/api/v1/admin/trials", await tokenFor(adminId, UserRole.OPS_ADMIN), trialInput({ sourceTrialId: "duplicate-source" })); const invalid = await request("POST", "/api/v1/admin/trials", await tokenFor(adminId, UserRole.OPS_ADMIN), { ...trialInput({ sourceTrialId: "invalid" }), source: "INVALID" }); assert.equal(duplicate.status, 409); assert.equal(invalid.status, 400); assert.equal(invalid.body.error.code, "VALIDATION_ERROR"); });

test("admin can manage interest status and roles are enforced", async () => { const trial = await createTrial({ title: "Admin interest trial", sourceTrialId: "admin-interest-1", isPublished: true }); const created = await request("POST", `/api/v1/trials/${trial.id}/interest`, await tokenFor(patientId), {}); interestIds.push(created.body.data.interestId); const list = await request("GET", "/api/v1/admin/trial-interests", await tokenFor(adminId, UserRole.OPS_ADMIN)); const updated = await request("PATCH", `/api/v1/admin/trial-interests/${created.body.data.interestId}/status`, await tokenFor(adminId, UserRole.OPS_ADMIN), { status: "CONTACTED" }); const patientAdmin = await request("GET", "/api/v1/admin/trials", await tokenFor(patientId)); const doctor = await request("GET", "/api/v1/admin/trials", await tokenFor(doctorId, UserRole.DOCTOR)); const unauthenticated = await request("GET", "/api/v1/trials"); assert.equal(list.body.data.items.some((item: { interestId: string }) => item.interestId === created.body.data.interestId), true); assert.equal(updated.body.data.status, "CONTACTED"); assert.equal(patientAdmin.status, 403); assert.equal(doctor.status, 403); assert.equal(unauthenticated.status, 401); });

async function createTrial(input: { title: string; sourceTrialId: string; isPublished: boolean; status?: ClinicalTrialStatus }) { const { prisma } = await import("../src/database/prisma"); const trial = await prisma.clinicalTrial.create({ data: { ...trialInput({ title: input.title, sourceTrialId: input.sourceTrialId, isPublished: input.isPublished, status: input.status }), createdById: adminId, updatedById: adminId, publishedAt: input.isPublished ? new Date() : null } }); trialIds.push(trial.id); return trial; }
function trialInput(input: { title?: string; sourceTrialId: string; isPublished?: boolean; status?: ClinicalTrialStatus }) { return { title: input.title ?? "Demo curated trial", summary: "Fictional demo trial summary.", description: "Fictional demo information for manual review only.", source: ClinicalTrialSource.OTHER, sourceTrialId: input.sourceTrialId, sourceUrl: "https://example.com/demo-trial", sponsor: "Demo sponsor", location: "Demo location", status: input.status ?? ClinicalTrialStatus.UNKNOWN, eligibilitySummary: "Demo eligibility summary.", contactInformation: "Demo contact information.", isPublished: input.isPublished ?? false }; }
async function createUser(prisma: typeof import("../src/database/prisma").prisma, name: string, role: UserRole) { return prisma.user.create({ data: { fullName: `${testKey} ${name}`, email: `${testKey}-${name}@example.com`, phone: `+1555${String(Math.floor(Math.random() * 10_000_000)).padStart(7, "0")}`, role, isVerified: true } }); }
async function tokenFor(userId: string, role = UserRole.PATIENT) { const { generateAccessToken } = await import("../src/services/jwt"); return generateAccessToken({ userId, role }); }
async function request(method: string, path: string, token?: string, body?: Record<string, unknown>) { const response = await fetch(`${baseUrl}${path}`, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: response.status, body: await response.json() as Record<string, any> }; }
