import { readAuthSession, writeAuthSession } from "../auth/storage";

type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ApiRequestOptions = Omit<
  RequestInit,
  "body" | "headers" | "method" | "signal"
> & {
  accessToken?: string;
  body?: unknown;
  headers?: HeadersInit;
  /**
   * Per-request timeout in milliseconds. Requests that exceed it fail with a
   * TimeoutError instead of hanging forever (which would leave spinners stuck).
   * Set to `0` to disable the timeout for a specific request.
   */
  timeoutMs?: number;
  /** Optional abort signal for cooperative cancellation by callers. */
  signal?: AbortSignal | null;
};

/** Default per-request timeout, generous enough for slow connections and file uploads. */
const DEFAULT_TIMEOUT_MS = 30_000;

export type AccessTokenProvider = () => string | null | undefined;

type ApiErrorResponse = {
  success: false;
  error: {
    code: string;
    message: string;
    /** Server-side correlation reference (Phase 4.7); absent on older responses. */
    requestId?: string;
  };
};

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  /**
   * Opaque server-assigned correlation reference for support/debugging.
   * Contains no PII — it is a random ID generated by the backend.
   */
  readonly requestId: string | null;

  constructor(status: number, code: string, message: string, requestId: string | null = null) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.code = code;
    this.requestId = requestId;
  }
}

/**
 * Builds the user-safe support suffix for an error: a short correlation
 * reference the user can quote. Only shown when the backend supplied a
 * request ID. Never includes tokens, identifiers, or internals.
 */
export function errorReference(error: unknown): string | null {
  return error instanceof ApiError && error.requestId ? error.requestId : null;
}

export const AUTHENTICATION_INVALIDATED_EVENT = "oncoeasy:authentication-invalidated";

const REFRESH_PATH = "/api/v1/auth/refresh";
const LOGOUT_PATH = "/api/v1/auth/logout";

type RefreshSuccessResponse = {
  success: true;
  data: {
    accessToken: string;
    refreshToken: string;
  };
};

export class ApiClient {
  private readonly baseUrl: string;
  private readonly accessTokenProvider?: AccessTokenProvider;

  /** In-flight refresh promise shared by all 401'd requests in a burst. */
  private refreshPromise: Promise<boolean> | null = null;

  constructor(
    baseUrl = import.meta.env.VITE_API_BASE_URL,
    accessTokenProvider?: AccessTokenProvider
  ) {
    if (!baseUrl) {
      throw new Error("VITE_API_BASE_URL is not configured");
    }

    this.baseUrl = baseUrl.replace(/\/+$/, "");
    this.accessTokenProvider = accessTokenProvider;
  }

  get<T>(path: string, options?: ApiRequestOptions): Promise<T> {
    return this.request<T>("GET", path, options);
  }

  post<T>(path: string, body?: unknown, options?: ApiRequestOptions): Promise<T> {
    return this.request<T>("POST", path, { ...options, body });
  }

  postForm<T>(path: string, body: FormData, options?: ApiRequestOptions): Promise<T> {
    return this.request<T>("POST", path, { ...options, body });
  }

  put<T>(path: string, body?: unknown, options?: ApiRequestOptions): Promise<T> {
    return this.request<T>("PUT", path, { ...options, body });
  }

  patch<T>(
    path: string,
    body?: unknown,
    options?: ApiRequestOptions
  ): Promise<T> {
    return this.request<T>("PATCH", path, { ...options, body });
  }

  delete<T>(path: string, options?: ApiRequestOptions): Promise<T> {
    return this.request<T>("DELETE", path, options);
  }

  /**
   * Authenticated binary fetch. Used where an element cannot send the bearer
   * token itself (for example an admin media preview of private objects).
   */
  async getBlob(path: string, options?: Omit<ApiRequestOptions, "body">): Promise<Blob> {
    let response = await this.sendBlobRequest(path, options);

    // Same single-flight refresh + one bounded retry as request(): an expired
    // access token on a media fetch transparently recovers instead of showing
    // a broken preview.
    if (response.status === 401 && this.shouldAttemptRefresh(options ?? {})) {
      const refreshed = await this.refreshOnce();

      if (refreshed) {
        response = await this.sendBlobRequest(path, options);
      }
    }

    if (!response.ok) {
      const body = await readResponseBody(response).catch(() => undefined);
      throw createApiError(response, body);
    }

    return response.blob();
  }

  private async sendBlobRequest(
    path: string,
    options?: Omit<ApiRequestOptions, "body">
  ): Promise<Response> {
    const headers = new Headers(options?.headers);
    const accessToken = options?.accessToken ?? this.accessTokenProvider?.();
    if (accessToken) {
      headers.set("Authorization", `Bearer ${accessToken}`);
    }

    try {
      return await fetchWithTimeout(`${this.baseUrl}${path}`, toFetchInit(options ?? {}, {
        method: "GET",
        headers
      }));
    } catch (requestError) {
      if (isAbortError(requestError)) {
        throw requestError;
      }

      if (requestError instanceof TimeoutError) {
        throw new ApiError(0, "TIMEOUT", "The request timed out. Please try again.");
      }

      throw new ApiError(
        0,
        "NETWORK_ERROR",
        "Unable to connect. Check your connection and try again."
      );
    }
  }

  private async request<T>(
    method: HttpMethod,
    path: string,
    options: ApiRequestOptions = {}
  ): Promise<T> {
    let response = await this.sendRequest(method, path, options);

    // A 401 on a client-authenticated request usually means the short-lived
    // access token expired. Attempt exactly one refresh, then retry the
    // original request exactly once. The refresh call is issued with raw
    // fetch (never through request()) and the retry is bounded to one
    // attempt, so neither recursion nor infinite retry loops are possible.
    if (
      response.status === 401 &&
      this.shouldAttemptRefresh(options)
    ) {
      const refreshed = await this.refreshOnce();

      if (refreshed) {
        response = await this.sendRequest(method, path, options);
      }
    }

    const responseBody = await readResponseBody(response);

    if (!response.ok) {
      throw createApiError(response, responseBody);
    }

    return responseBody as T;
  }

  private async sendRequest(
    method: HttpMethod,
    path: string,
    options: ApiRequestOptions
  ): Promise<Response> {
    const headers = new Headers(options.headers);
    headers.set("Accept", "application/json");

    if (options.body !== undefined && !(options.body instanceof FormData)) {
      headers.set("Content-Type", "application/json");
    }

    // Re-read the provider on every attempt so a retry after a successful
    // refresh sends the freshly rotated access token.
    const accessToken = options.accessToken ?? this.accessTokenProvider?.();
    if (accessToken) {
      headers.set("Authorization", `Bearer ${accessToken}`);
    }

    try {
      return await fetchWithTimeout(`${this.baseUrl}${path}`, toFetchInit(options, {
        method,
        headers,
        body:
          options.body === undefined
            ? undefined
            : options.body instanceof FormData
              ? options.body
              : JSON.stringify(options.body)
      }));
    } catch (requestError) {
      // Caller-initiated cancellation propagates untouched; everything else at
      // the transport layer (offline, DNS, refused connection, timeout) is
      // normalized to an ApiError so every page's error handling renders the
      // user-safe message instead of a raw TypeError or generic fallback.
      if (isAbortError(requestError)) {
        throw requestError;
      }

      if (requestError instanceof TimeoutError) {
        throw new ApiError(0, "TIMEOUT", "The request timed out. Please try again.");
      }

      throw new ApiError(
        0,
        "NETWORK_ERROR",
        "Unable to connect. Check your connection and try again."
      );
    }
  }

  /**
   * Refresh is only attempted for requests authenticated from stored session
   * state. Requests carrying a caller-provided token are never refreshed —
   * those credentials are managed by their callers.
   */
  private shouldAttemptRefresh(options: ApiRequestOptions): boolean {
    if (options.accessToken) {
      return false;
    }

    return Boolean(readAuthSession()?.refreshToken);
  }

  /**
   * Single-flight refresh: concurrent 401s awaiting refresh share this
   * promise, so one burst of expired-token requests produces exactly ONE
   * refresh call. The slot is freed as soon as it settles so a later burst
   * can refresh again.
   */
  private refreshOnce(): Promise<boolean> {
    if (!this.refreshPromise) {
      this.refreshPromise = this.performRefresh().finally(() => {
        this.refreshPromise = null;
      });
    }

    return this.refreshPromise;
  }

  /**
   * Exchanges the stored refresh token for a rotated token pair. On failure
   * the original request's 401 escapes to the caller, whose error path
   * broadcasts AUTHENTICATION_INVALIDATED_EVENT and clears the session —
   * every waiting request fails cleanly, with no retry loop.
   */
  private async performRefresh(): Promise<boolean> {
    const currentSession = readAuthSession();
    if (!currentSession?.refreshToken) {
      return false;
    }

    try {
      const response = await fetchWithTimeout(`${this.baseUrl}${REFRESH_PATH}`, {
        method: "POST",
        headers: new Headers({ "Accept": "application/json", "Content-Type": "application/json" }),
        body: JSON.stringify({ refreshToken: currentSession.refreshToken })
      });

      const body = (await readResponseBody(response)) as unknown;

      if (!response.ok || !isRefreshSuccess(body)) {
        return false;
      }

      // Persist the rotated pair immediately so the retrying request — and
      // any request that starts afterwards — sends the fresh access token.
      writeAuthSession({
        ...currentSession,
        accessToken: body.data.accessToken,
        refreshToken: body.data.refreshToken
      });
      return true;
    } catch {
      // Network/timeout failure while refreshing: the original 401 response
      // is still surfaced to the caller, which cleans the session up.
      return false;
    }
  }
}

export class TimeoutError extends Error {
  constructor(message = "The request timed out. Please try again.") {
    super(message);
    this.name = "TimeoutError";
  }
}

/**
 * Fire-and-forget server-side revocation of the stored refresh session during
 * logout. Deliberately unawaited and failure-tolerant: local cleanup must
 * always complete, and short-lived access tokens bound the residual exposure
 * window until expiry. The token is read before the caller clears storage.
 */
export function revokeSessionOnLogout(): void {
  const currentSession = readAuthSession();
  if (!currentSession?.refreshToken) {
    return;
  }

  const baseUrl = (import.meta.env.VITE_API_BASE_URL ?? "").replace(/\/+$/, "");

  void fetch(`${baseUrl}${LOGOUT_PATH}`, {
    method: "POST",
    headers: new Headers({ "Content-Type": "application/json" }),
    body: JSON.stringify({ refreshToken: currentSession.refreshToken }),
    keepalive: true
  }).catch(() => undefined);
}

/**
 * Builds the platform RequestInit for fetch from ApiClient options plus the
 * per-call method/headers/body, passing through standard fetch fields.
 */
function toFetchInit(
  options: ApiRequestOptions,
  core: Pick<RequestInit, "method" | "headers" | "body">
): RequestInit & { timeoutMs?: number } {
  return {
    method: core.method,
    headers: core.headers,
    body: core.body,
    cache: options.cache,
    credentials: options.credentials,
    integrity: options.integrity,
    keepalive: options.keepalive,
    mode: options.mode,
    redirect: options.redirect,
    referrer: options.referrer,
    referrerPolicy: options.referrerPolicy,
    signal: options.signal ?? undefined,
    timeoutMs: options.timeoutMs
  };
}

/**
 * fetch with a timeout race. Aborts the in-flight request when the deadline
 * expires so hung sockets cannot leave the UI loading forever.
 */
async function fetchWithTimeout(
  url: string,
  init: RequestInit & { timeoutMs?: number }
): Promise<Response> {
  const timeoutMs = init.timeoutMs === undefined ? DEFAULT_TIMEOUT_MS : init.timeoutMs;
  const callerSignal = init.signal ?? undefined;
  const requestInit: RequestInit = {
    method: init.method,
    headers: init.headers,
    body: init.body,
    cache: init.cache,
    credentials: init.credentials,
    integrity: init.integrity,
    keepalive: init.keepalive,
    mode: init.mode,
    redirect: init.redirect,
    referrer: init.referrer,
    referrerPolicy: init.referrerPolicy,
    signal: init.signal
  };

  if (!timeoutMs) {
    return fetch(url, requestInit);
  }

  const controller = new AbortController();
  let timedOut = false;

  function handleAbort(): void {
    controller.abort();
  }

  if (callerSignal) {
    if (callerSignal.aborted) {
      controller.abort();
    } else {
      callerSignal.addEventListener("abort", handleAbort, { once: true });
    }
  }

  const timer = window.setTimeout(() => {
    timedOut = true;
    controller.abort();
  }, timeoutMs);

  try {
    return await fetch(url, { ...requestInit, signal: controller.signal });
  } catch (error) {
    if (timedOut && !isAbortError(error)) {
      throw new TimeoutError();
    }
    throw error;
  } finally {
    window.clearTimeout(timer);
    if (callerSignal) {
      callerSignal.removeEventListener("abort", handleAbort);
    }
  }
}

function isAbortError(error: unknown): boolean {
  return error instanceof DOMException && error.name === "AbortError";
}

/**
 * Builds an absolute URL for a backend-provided asset path (for example a
 * testimonial media delivery URL). Absolute provider URLs pass through as-is.
 */
export function apiAssetUrl(path: string | null | undefined): string | null {
  if (!path) {
    return null;
  }

  if (/^https?:\/\//i.test(path)) {
    return path;
  }

  const baseUrl = (import.meta.env.VITE_API_BASE_URL ?? "").replace(/\/+$/, "");
  return `${baseUrl}${path.startsWith("/") ? "" : "/"}${path}`;
}

async function readResponseBody(response: Response): Promise<unknown> {
  if (response.status === 204) {
    return undefined;
  }

  const contentType = response.headers.get("content-type");
  if (contentType?.includes("application/json")) {
    // A 200 response with a truncated/invalid JSON body should surface as a
    // generic request failure rather than an unhandled parse exception.
    return response.json().catch(() => undefined);
  }

  const text = await response.text();
  return text || undefined;
}

function createApiError(response: Response, body: unknown): ApiError {
  if (isApiErrorResponse(body)) {
    const error = new ApiError(
      response.status,
      body.error.code,
      body.error.message,
      body.error.requestId ?? null
    );
    notifyAuthenticationInvalidated(response.status);
    return error;
  }

  const error = new ApiError(
    response.status,
    "HTTP_ERROR",
    response.statusText || "The request failed"
  );
  notifyAuthenticationInvalidated(response.status);
  return error;
}

function notifyAuthenticationInvalidated(status: number): void {
  if (status === 401 && typeof window !== "undefined") {
    window.dispatchEvent(new Event(AUTHENTICATION_INVALIDATED_EVENT));
  }
}

function isApiErrorResponse(value: unknown): value is ApiErrorResponse {
  if (typeof value !== "object" || value === null) {
    return false;
  }

  const response = value as Record<string, unknown>;
  const error = response.error;

  return (
    response.success === false &&
    typeof error === "object" &&
    error !== null &&
    typeof (error as Record<string, unknown>).code === "string" &&
    typeof (error as Record<string, unknown>).message === "string"
  );
}

function isRefreshSuccess(value: unknown): value is RefreshSuccessResponse {
  if (typeof value !== "object" || value === null) {
    return false;
  }

  const data = (value as Record<string, unknown>).data;
  return (
    typeof data === "object" &&
    data !== null &&
    typeof (data as Record<string, unknown>).accessToken === "string" &&
    typeof (data as Record<string, unknown>).refreshToken === "string"
  );
}

export const apiClient = new ApiClient(undefined, () => {
  return readAuthSession()?.accessToken;
});